name: Coverage

on: [push]

env:
  CXXFLAGS: "-O0 --coverage -fno-inline -fno-inline-small-functions -fno-default-inline"
  CXX: g++
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

jobs:
  codecov:
    runs-on: ubuntu-latest

    steps:      
      - uses: actions/checkout@v2
      - name: Create Build Environment
        run: git submodule update --init

      - name: Configure CMake
        working-directory: build
        run: cmake .. -DECSPP_BENCHMARKS=OFF

      - name: Build
        working-directory: build
        run: cmake --build .

      - name: Test
        working-directory: build
        run: ctest
        
      - name: Upload coverage to Codecov
        working-directory: build
        run: |
          wget https://codecov.io/bash -O codecov
          chmod +x ./codecov
          ./codecov -t $CODECOV_TOKEN -B $GITHUB_REF -f '!*#external#*' -s .
